# Generated by Django 5.0 on 2023-12-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts_title', models.CharField(blank=True, default='Контакти', max_length=255, null=True, verbose_name='Зміст контактів')),
                ('contacts_info_text', models.TextField(blank=True, default='TOBIBOX', null=True, verbose_name='Інформація про контакти')),
            ],
        ),
    ]
