# Generated by Django 5.0 on 2023-12-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TOBIBOX', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsinfo',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакти'},
        ),
    ]
