# Generated by Django 5.0 on 2023-12-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOBIBOX', '0002_alter_contactsinfo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(default='Наша команда', help_text='Заголовок раздела "Про нас"', max_length=30, verbose_name='Про нас (title)')),
                ('about_info_text', models.TextField(default='TOBIBOX', help_text='Текст с информацией о вашей команде', verbose_name='Інформація про нас')),
            ],
            options={
                'verbose_name': 'Про нас',
                'verbose_name_plural': 'Про нас',
            },
        ),
        migrations.AlterField(
            model_name='contactsinfo',
            name='contacts_title',
            field=models.CharField(blank=True, default='Контакти', max_length=30, null=True, verbose_name='Контакти (title)'),
        ),
    ]
