# Generated by Django 5.0 on 2023-12-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOBIBOX', '0003_aboutinfo_alter_contactsinfo_contacts_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(auto_created=True, verbose_name='Дата та час')),
                ('post_title', models.CharField(max_length=30, verbose_name='Зміст посту')),
                ('post_content', models.TextField(verbose_name='Опис новини')),
                ('post_img', models.ImageField(default='', upload_to='posters/', verbose_name='Постер')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Пости',
            },
        ),
        migrations.AlterField(
            model_name='aboutinfo',
            name='about_info_text',
            field=models.TextField(default='TOBIBOX', help_text='Текст з інформацією про вашу команду', verbose_name='Інформація про нас'),
        ),
    ]
