# Generated by Django 5.0 on 2023-12-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOBIBOX', '0004_indexpost_alter_aboutinfo_about_info_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpost',
            name='post_img',
            field=models.ImageField(blank=True, upload_to='posters/', verbose_name='Постер'),
        ),
    ]
