# Generated by Django 5.0 on 2023-12-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOBIBOX', '0005_alter_indexpost_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpost',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата та час'),
        ),
    ]
