# Generated by Django 5.0 on 2023-12-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOBIBOX', '0007_boxcategory_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_one', models.ImageField(blank=True, upload_to='carousel/', verbose_name='Зображення 1')),
                ('img_two', models.ImageField(blank=True, upload_to='carousel/', verbose_name='Зображення 2')),
                ('img_three', models.ImageField(blank=True, upload_to='carousel/', verbose_name='Зображення 3')),
            ],
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='post_img',
            field=models.ImageField(blank=True, upload_to='other_img/', verbose_name='Значок/пiдпис'),
        ),
    ]
