# Generated by Django 5.0 on 2023-12-26 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TOBIBOX', '0008_carouselimg_aboutinfo_post_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselimg',
            options={'verbose_name': 'Карусель', 'verbose_name_plural': 'Каруселi'},
        ),
    ]
