# Generated by Django 5.0 on 2023-12-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOBIBOX', '0009_alter_carouselimg_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimg',
            name='carousel_title',
            field=models.CharField(default='Карусель', help_text='Карусель', max_length=30, verbose_name='Карусель'),
        ),
    ]
