# Generated by Django 5.0 on 2024-01-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOBIBOX', '0011_drawtemplates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawtemplates',
            name='templates_upload',
            field=models.FileField(upload_to='drawing_templates/', verbose_name='Завантаження креслення'),
        ),
    ]
