# Generated by Django 5.0 on 2024-01-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOBIBOX', '0012_alter_drawtemplates_templates_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawtemplates',
            name='draw_content',
            field=models.TextField(default=1, verbose_name='Опис креслення'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drawtemplates',
            name='templates_prev',
            field=models.ImageField(default='static/TOBIBOX/svg/favicon.svg', upload_to='drawing_templates/', verbose_name="Прев'ю"),
        ),
    ]
