# Generated by Django 5.0 on 2024-01-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOBIBOX', '0014_drawtemplates_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawtemplates',
            name='name',
            field=models.CharField(help_text='Назва файлу без розширення', max_length=30, verbose_name='Назва файлу'),
        ),
    ]
