# Generated by Django 5.0 on 2024-01-02 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TOBIBOX', '0016_alter_drawtemplates_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drawtemplates',
            old_name='name',
            new_name='file_name',
        ),
    ]
