# Generated by Django 5.0 on 2024-01-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOBIBOX', '0017_rename_name_drawtemplates_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawtemplates',
            name='max_material',
            field=models.IntegerField(default=500, max_length=5, verbose_name='Максимальна товщина матерiалу'),
        ),
        migrations.AddField(
            model_name='drawtemplates',
            name='min_material',
            field=models.IntegerField(default=360, max_length=5, verbose_name='Мінімальна товщина матерiалу'),
        ),
        migrations.AlterField(
            model_name='drawtemplates',
            name='max_depth',
            field=models.IntegerField(max_length=5, verbose_name='Максимальна глибина'),
        ),
        migrations.AlterField(
            model_name='drawtemplates',
            name='min_depth',
            field=models.IntegerField(max_length=5, verbose_name='Мінімальна глибина'),
        ),
    ]
