# Generated by Django 5.0 on 2024-01-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOBIBOX', '0019_alter_drawtemplates_max_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawtemplates',
            name='max_depth',
            field=models.IntegerField(max_length=5, verbose_name='Макс. глибина'),
        ),
        migrations.AlterField(
            model_name='drawtemplates',
            name='max_height',
            field=models.IntegerField(max_length=5, verbose_name='Макс. висота'),
        ),
        migrations.AlterField(
            model_name='drawtemplates',
            name='max_material',
            field=models.IntegerField(default=500, max_length=5, null=True, verbose_name='Макс. тов. матерiалу'),
        ),
        migrations.AlterField(
            model_name='drawtemplates',
            name='max_width',
            field=models.IntegerField(max_length=5, verbose_name='Макс. ширина'),
        ),
        migrations.AlterField(
            model_name='drawtemplates',
            name='min_depth',
            field=models.IntegerField(max_length=5, verbose_name='Мін. глибина'),
        ),
        migrations.AlterField(
            model_name='drawtemplates',
            name='min_height',
            field=models.IntegerField(max_length=5, verbose_name='Мін. висота'),
        ),
        migrations.AlterField(
            model_name='drawtemplates',
            name='min_material',
            field=models.IntegerField(default=360, max_length=5, null=True, verbose_name='Мін. тов. матерiалу'),
        ),
        migrations.AlterField(
            model_name='drawtemplates',
            name='min_width',
            field=models.IntegerField(max_length=5, verbose_name='Мін. ширина'),
        ),
        migrations.AlterField(
            model_name='drawtemplates',
            name='templates_upload',
            field=models.FileField(upload_to='drawing_templates/', verbose_name='Креслення'),
        ),
    ]
