# Generated by Django 5.0 on 2024-01-06 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TOBIBOX', '0021_socialmediaothersettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmediaothersettings',
            options={'verbose_name': 'Соц налаштування', 'verbose_name_plural': 'Соц налаштування'},
        ),
    ]
