# Generated by Django 5.0 on 2024-01-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TOBIBOX', '0022_alter_socialmediaothersettings_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialMediaOtherSettings',
            new_name='SocialMedia',
        ),
    ]
